#!/usr/bin/env bash
#creat a file and kill it
sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
pid=$$
echo $pid > /var/run/myscript.pid
i=1
while [ $i ]
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo I hate the kill command && rm /var/run/myscript.pid && exit" SIGTERM
    trap "echo Y U no love me?!" SIGINT
    trap "rm /var/run/myscript.pid && exit" SIGQUIT
done
