#!/usr/bin/env bash
# Display bad lack on 4 and good lack on 8 the rest Best School
i=1
while ((i <= 10))
do
	if ((i == 4 ))
	then
		echo 'bad luck'
	elif ((i == 8))
	then
		echo 'good luck'
	else
		echo 'Best School'
	fi
	((i++))
done
