#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes
hrs=0
mins=1
while ((hrs <= 12))
do
	echo "Hour: $hrs"
	while ((mins < 60))
	do
		echo "$mins"
		((mins++))
	done
	mins=1
	((hrs++))
done
