#!/usr/bin/env bash
# Change localhost to 127.0.0.2 and facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i s/^127.*$/127.0.0.2\\tlocalhost/g ~/hosts.new
sed -i '1 a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
